export const journals = [
  {
    id: 1,
    title: "Annals of Cardiology & Vascular Medicine",
    issn: "ISSN: 2639-4383",
    description: "Advancing cardiovascular science through rigorous peer-reviewed research covering heart disease, vascular disorders, and interventional therapies.",
    icon: "❤️",
    color: "#e53e3e",
    bg: "#fff5f5",
    articles: 142,
  },
  {
    id: 2,
    title: "Journal of Neurology & Neurological Sciences",
    issn: "ISSN: 2692-3548",
    description: "Exploring the frontiers of brain science — from neurodegenerative diseases to cutting-edge neuroimaging and clinical neurology.",
    icon: "🧠",
    color: "#6b46c1",
    bg: "#faf5ff",
    articles: 98,
  },
  {
    id: 3,
    title: "Annals of Gastroenterology & Digestive System",
    issn: "ISSN: 2637-4501",
    description: "Comprehensive coverage of gastrointestinal health, liver diseases, endoscopic procedures, and nutrition-related disorders.",
    icon: "🔬",
    color: "#2f855a",
    bg: "#f0fff4",
    articles: 115,
  },
  {
    id: 4,
    title: "Journal of Nanomedicine",
    issn: "ISSN: 2578-8760",
    description: "At the intersection of nanotechnology and medicine — drug delivery systems, biosensors, nanoparticle therapy, and diagnostic innovation.",
    icon: "⚛️",
    color: "#0097a7",
    bg: "#e0f7fa",
    articles: 87,
  },
  {
    id: 5,
    title: "Annals of Biotechnology",
    issn: "ISSN: 2578-9945",
    description: "Covering genetic engineering, biopharmaceuticals, industrial fermentation, and the latest breakthroughs in life sciences technology.",
    icon: "🧬",
    color: "#c8963e",
    bg: "#fffbf0",
    articles: 76,
  },
  {
    id: 6,
    title: "Journal of Addiction & Recovery",
    issn: "ISSN: 2576-9782",
    description: "Dedicated to evidence-based approaches in addiction medicine, behavioral health, rehabilitation, and substance use disorder management.",
    icon: "🌱",
    color: "#38a169",
    bg: "#f0fff4",
    articles: 63,
  },
];

export const recentArticles = [
  {
    id: 1,
    title: "Effects of SGLT2 Inhibitor on Neurohormonal Activity and Electrolyte Management in an Elderly Patient with Acute Heart Failure",
    authors: "Hajime Kataoka",
    journal: "Annals of Cardiology and Vascular Medicine",
    date: "March 2024",
    type: "Case Report",
    color: "#e53e3e",
  },
  {
    id: 2,
    title: "A Review of Gastrointestinal Effects Associated with COVID-19 Infections",
    authors: "Bailey Reid; Allyson L. Spence; Cassandra Stroup",
    journal: "Annals of Gastroenterology and Digestive System",
    date: "February 2024",
    type: "Review Article",
    color: "#2f855a",
  },
  {
    id: 3,
    title: "Nanoparticles Mitigate Retinal Pigment Epithelium Death Using APRE19 Cell Model",
    authors: "Eric Dahl; Nikolaos E. Efstathiou; Amit K. Roy",
    journal: "Journal of Nanomedicine",
    date: "January 2024",
    type: "Research Article",
    color: "#0097a7",
  },
  {
    id: 4,
    title: "Novel Biomarkers for Early Detection of Neurodegenerative Disorders: A Systematic Review",
    authors: "Sarah Chen; Michael Torres; Priya Nair",
    journal: "Journal of Neurology & Neurological Sciences",
    date: "December 2023",
    type: "Systematic Review",
    color: "#6b46c1",
  },
];

export const allJournals = [
  { id: 1, title: "Annals of Anesthesia and Pain Medicine", url: "https://meddocsonline.org/annals-of-anesthesia-and-pain-medicine.html", category: "Anesthesia" },
  { id: 2, title: "Annals of Bariatrics & Metabolic Surgery", url: "https://meddocsonline.org/annals-of-bariatrics-metabolic-surgery.html", category: "Surgery" },
  { id: 3, title: "Annals of Biotechnology", url: "https://meddocsonline.org/annals-of-biotechnology.html", category: "Biotechnology" },
  { id: 4, title: "Annals of Breast Cancer", url: "https://meddocsonline.org/annals-of-breast-cancer.html", category: "Oncology" },
  { id: 5, title: "Annals of Cardiology and Vascular Medicine", url: "https://meddocsonline.org/annals-of-cardiology-and-vascular-medicine.html", category: "Cardiology" },
  { id: 6, title: "Annals of Clinical Nutrition", url: "https://meddocsonline.org/annals-of-clinical-nutrition.html", category: "Nutrition" },
  { id: 7, title: "Annals of Dentistry and Oral Health", url: "https://meddocsonline.org/annals-of-dentistry-and-oral-health.html", category: "Dentistry" },
  { id: 8, title: "Annals of Epidemiology and Public Health", url: "https://meddocsonline.org/annals-of-epidemiology-and-public-health.html", category: "Public Health" },
  { id: 9, title: "Annals of Gastroenterology and the Digestive System", url: "https://meddocsonline.org/annals-of-gastroenterology-and-the-digestive-system.html", category: "Gastroenterology" },
  { id: 10, title: "Annals of Gynecologic Cancer", url: "https://meddocsonline.org/annals-of-gynecologic-cancer.html", category: "Oncology" },
  { id: 11, title: "Annals of Infectious Diseases & Preventive Medicine", url: "https://meddocsonline.org/annals-of-infectious-diseases-and-preventive-medicine.html", category: "Infectious Diseases" },
  { id: 12, title: "Annals of Nursing and Health Care", url: "https://meddocsonline.org/annals-of-nursing-and-health-care.html", category: "Nursing" },
  { id: 13, title: "Annals of Obstetrics and Gynecology", url: "https://meddocsonline.org/annals-of-obstetrics-and-gynecology.html", category: "Gynecology" },
  { id: 14, title: "Annals of Ophthalmology and Visual Sciences", url: "https://meddocsonline.org/annals-of-ophthalmology-and-visual-sciences.html", category: "Ophthalmology" },
  { id: 15, title: "Annals of Pediatrics", url: "https://meddocsonline.org/annals-of-pediatrics.html", category: "Pediatrics" },
  { id: 16, title: "Annals of Reproductive Medicine", url: "https://meddocsonline.org/annals-of-reproductive-medicine.html", category: "Reproductive Medicine" },
  { id: 17, title: "Annals of Dementia", url: "https://meddocsonline.org/annals-of-dementia.html", category: "Neurology" },
  { id: 18, title: "Annals of Anatomy & Research", url: "https://meddocsonline.org/annals-of-anatomy-and-research.html", category: "Anatomy" },
  { id: 19, title: "Annals of Cardiology Case Reports", url: "https://meddocsonline.org/annals-of-cardiology-case-reports.html", category: "Cardiology" },
  { id: 20, title: "Annals of Forensic Science and Research", url: "https://meddocsonline.org/annals-of-forensic-science-and-research.html", category: "Forensic Science" },
  { id: 21, title: "Annals of Urology Research & Practice", url: "https://meddocsonline.org/annals-of-urology-research-and-practice.html", category: "Urology" },
  { id: 22, title: "Annals of Bacteriology Research", url: "https://meddocsonline.org/annals-of-bacteriology-research.html", category: "Microbiology" },
  { id: 23, title: "Annals of Dermatology Research and Practice", url: "https://meddocsonline.org/annals-of-dermatology-research-and-practice.html", category: "Dermatology" },
  { id: 24, title: "Annals of Pharmaceutical Sciences", url: "https://meddocsonline.org/annals-of-pharmaceutical-sciences.html", category: "Pharmacology" },
  { id: 25, title: "Annals of Immunology Research", url: "https://meddocsonline.org/annals-of-immunology-research.html", category: "Immunology" },
  { id: 26, title: "Annals of Endocrinology, Diabetes and Metabolism", url: "https://meddocsonline.org/annals-of-endocrinology-diabetes-and-metabolism.html", category: "Endocrinology" },
  { id: 27, title: "Annals of Infectious Diseases", url: "https://meddocsonline.org/annals-of-infectious-diseases.html", category: "Infectious Diseases" },
  { id: 28, title: "Annals of Oncology Case Reports", url: "https://meddocsonline.org/annals-of-oncology-case-reports.html", category: "Oncology" },
  { id: 29, title: "Annals of Community Medicine and Primary Health Care", url: "https://meddocsonline.org/annals-of-community-medicine-and-primary-health-care.html", category: "Public Health" },
  { id: 30, title: "Annals of Human Nutrition and Dietetics", url: "https://meddocsonline.org/annals-of-human-nutrition-and-dietetics.html", category: "Nutrition" },
  { id: 31, title: "Annals of Aquaculture and Marine Biology", url: "https://meddocsonline.org/annals-of-aquaculture-and-marine-biology.html", category: "Biology" },
  { id: 32, title: "Annals of HIV/AIDS Research", url: "https://meddocsonline.org/annals-of-hiv-aids-research.html", category: "Infectious Diseases" },
  { id: 33, title: "Annals of Otolaryngology Research", url: "https://meddocsonline.org/annals-of-otolaryngology-research.html", category: "ENT" },
  { id: 34, title: "Annals of Cancer Research", url: "https://meddocsonline.org/annals-of-cancer-research.html", category: "Oncology" },
  { id: 35, title: "Annals of Organic and Inorganic Chemistry", url: "https://meddocsonline.org/annals-of-organic-and-inorganic-chemistry.html", category: "Chemistry" },
  { id: 36, title: "Annals of Hematology and Blood Disorders", url: "https://meddocsonline.org/annals-of-hematology-and-blood-disorders.html", category: "Hematology" },
  { id: 37, title: "Annals of Textile Engineering and Fashion Technology", url: "https://meddocsonline.org/annals-of-textile-engineering-and-fashion-technology.html", category: "Engineering" },
  { id: 38, title: "Annals of Orthopedics and Sports Medicine", url: "https://meddocsonline.org/annals-of-orthopedics-and-sports-medicine.html", category: "Orthopedics" },
  { id: 39, title: "Annals of Neurology and Neurosurgery", url: "https://meddocsonline.org/annals-of-neurology-and-neurosurgery.html", category: "Neurology" },
  { id: 40, title: "International Journal of Innovative Surgery", url: "https://meddocsonline.org/international-journal-of-innovative-surgery.html", category: "Surgery" },
  { id: 41, title: "Journal of Abdominal Wall Reconstruction", url: "https://meddocsonline.org/journal-of-abdominal-wall-reconstruction.html", category: "Surgery" },
  { id: 42, title: "Journal of Addiction & Recovery", url: "https://meddocsonline.org/journal-of-addiction-recovery.html", category: "Psychiatry" },
  { id: 43, title: "Journal of Case Reports and Medical Images", url: "https://meddocsonline.org/journal-of-case-reports-and-medical-images.html", category: "Clinical Medicine" },
  { id: 44, title: "Journal of Clinical Images", url: "https://meddocsonline.org/journal-of-clinical-images.html", category: "Clinical Medicine" },
  { id: 45, title: "Journal of Community Medicine", url: "https://meddocsonline.org/journal-of-community-medicine.html", category: "Public Health" },
  { id: 46, title: "Journal of Nanomedicine", url: "https://meddocsonline.org/journal-of-nanomedicine.html", category: "Nanomedicine" },
  { id: 47, title: "Journal of Nephrology and Hypertension", url: "https://meddocsonline.org/journal-of-nephrology-and-hypertension.html", category: "Nephrology" },
  { id: 48, title: "Journal of Orthopedics and Muscular System", url: "https://meddocsonline.org/journal-of-orthopedics-and-muscular-system.html", category: "Orthopedics" },
  { id: 49, title: "Journal of Plant Biology and Crop Research", url: "https://meddocsonline.org/journal-of-plant-biology-and-crop-research.html", category: "Biology" },
  { id: 50, title: "Journal of Psychiatry and Behavioral Sciences", url: "https://meddocsonline.org/journal-of-psychiatry-and-behavioral-sciences.html", category: "Psychiatry" },
  { id: 51, title: "Journal of Radiology and Medical Imaging", url: "https://meddocsonline.org/journal-of-radiology-and-medical-imaging.html", category: "Radiology" },
  { id: 52, title: "Journal of Tuberculosis", url: "https://meddocsonline.org/journal-of-tuberculosis.html", category: "Infectious Diseases" },
  { id: 53, title: "Journal of Veterinary Medicine and Animal Sciences", url: "https://meddocsonline.org/journal-of-veterinary-medicine-and-animal-sciences.html", category: "Veterinary" },
  { id: 54, title: "Journal of Chronic Diseases Research", url: "https://meddocsonline.org/journal-of-chronic-diseases-research.html", category: "Clinical Medicine" },
  { id: 55, title: "Journal of Autism Research", url: "https://meddocsonline.org/journal-of-autism-research.html", category: "Psychiatry" },
  { id: 56, title: "Journal of Obesity and Disorders", url: "https://meddocsonline.org/journal-of-obesity-and-disorders.html", category: "Endocrinology" },
  { id: 57, title: "Journal of Gerontology and Aging Studies", url: "https://meddocsonline.org/journal-of-gerontology-and-aging-studies.html", category: "Geriatrics" },
  { id: 58, title: "Journal of Critical Care and Emergency Medicine", url: "https://meddocsonline.org/journal-of-critical-care-and-emergency-medicine.html", category: "Emergency Medicine" },
  { id: 59, title: "Journal of Family Medicine and Care", url: "https://meddocsonline.org/journal-of-family-medicine-and-care.html", category: "Family Medicine" },
  { id: 60, title: "Journal of Gynecology Case Reports", url: "https://meddocsonline.org/journal-of-gynecology-case-reports.html", category: "Gynecology" },
  { id: 61, title: "Journal of Surgery Case Reports", url: "https://meddocsonline.org/journal-of-surgery-case-reports.html", category: "Surgery" },
  { id: 62, title: "Neurology and Neurological Sciences: Open Access", url: "https://meddocsonline.org/neurology-and-neurological-sciences-open-access.html", category: "Neurology" },
  { id: 63, title: "Case Reports of Oncology: Open Access", url: "https://meddocsonline.org/case-reports-of-oncology-open-access.html", category: "Oncology" },
  { id: 64, title: "Chronicles of Oncology", url: "https://meddocsonline.org/chronicles-of-oncology.html", category: "Oncology" },
  { id: 65, title: "Hematology and Oncology Current Research", url: "https://meddocsonline.org/hematology-and-oncology-current-research.html", category: "Hematology" },
  { id: 66, title: "Depression and Anxiety: Open Access", url: "https://meddocsonline.org/depression-and-anxiety-open-access.html", category: "Psychiatry" },
  { id: 67, title: "MedDocs Biomedical Engineering", url: "https://meddocsonline.org/meddocs-biomedical-engineering.html", category: "Engineering" },
  { id: 68, title: "Nursing Research and Practice: Open Access", url: "https://meddocsonline.org/nursing-research-and-practice-open-access.html", category: "Nursing" },
  { id: 69, title: "Environmental Sciences: Open Access", url: "https://meddocsonline.org/environmental-sciences-open-access.html", category: "Environmental Science" },
  { id: 70, title: "Archives of Palliative Medicine", url: "https://meddocsonline.org/archives-of-palliative-medicine.html", category: "Palliative Care" },
  { id: 71, title: "MedDocs Microbiology", url: "https://meddocsonline.org/meddocs-microbiology.html", category: "Microbiology" },
  { id: 72, title: "Nanoscience and Nanotechnology: Open Access", url: "https://meddocsonline.org/nanoscience-and-nanotechnology-open-access.html", category: "Nanomedicine" },
];

export const ebooks = [
  { id: 1, title: "Alzheimer's Disease & Treatment", category: "Neurology", year: 2023, color: "#1e3a8a" },
  { id: 2, title: "Pharmaceutical Chemistry Essentials", category: "Pharmacology", year: 2023, color: "#1e3a8a" },
  { id: 3, title: "Vascular Diseases: A Clinical Guide", category: "Cardiology", year: 2022, color: "#1e3a8a" },
  { id: 4, title: "Importance & Applications of Nanotechnology", category: "Nanomedicine", year: 2023, color: "#1e3a8a" },
  { id: 5, title: "Principles of Modern Chemistry", category: "Chemistry", year: 2022, color: "#1e3a8a" },
  { id: 6, title: "Recent Trends in Biotechnology", category: "Biotechnology", year: 2023, color: "#1e3a8a" },
  { id: 7, title: "Research Trends of Microbiology", category: "Microbiology", year: 2022, color: "#1e3a8a" },
  { id: 8, title: "Transfusion Medicine Handbook", category: "Hematology", year: 2023, color: "#1e3a8a" },
];

export const conferences = [
  {
    id: 1,
    title: "World Congress on Cardiology & Cardiovascular Health",
    location: "Vienna, Austria",
    date: "June 14–16, 2024",
    status: "upcoming",
    delegates: 850,
    sessions: 42,
  },
  {
    id: 2,
    title: "International Summit on Neuroscience & Brain Disorders",
    location: "Tokyo, Japan",
    date: "July 22–24, 2024",
    status: "upcoming",
    delegates: 620,
    sessions: 35,
  },
  {
    id: 3,
    title: "Global Symposium on Nanomedicine & Drug Delivery",
    location: "London, UK",
    date: "September 5–7, 2024",
    status: "upcoming",
    delegates: 480,
    sessions: 28,
  },
];

export const stats = [
  { label: "Published Journals", value: "45+", icon: "📰" },
  { label: "Research Articles", value: "2,800+", icon: "📄" },
  { label: "Global Authors", value: "12,000+", icon: "👨‍🔬" },
  { label: "Countries Represented", value: "120+", icon: "🌍" },
];

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Journals", href: "#journals" },
  { label: "Articles", href: "#articles" },
  { label: "eBooks", href: "#ebooks" },
  { label: "Conferences", href: "#conferences" },
  { label: "Contact", href: "#contact" },
];
